### ISSUE TITLE
Augmented segmentation outcomes?

### ISSUE THREAD

**Issue by ahinchoi** [takaniwa/DSNet#21]
Hi!

First of all, congratulations on your great work.

While trying to reproduce the results on my custom dataset, I have become curious as to the differences between the three different segmentation maps your model outputs. 

The second one seems to be the main prediction according to your code, but what do the other segmentation maps mean, and what purpose do they achieve during training and inference?

Thank you in advance!

Regards.

**Comment by takaniwa** [comment]
> Hi!
> 
> First of all, congratulations on your great work.
> 
> While trying to reproduce the results on my custom dataset, I have become curious as to the differences between the three different segmentation maps your model outputs.
> 
> The second one seems to be the main prediction according to your code, but what do the other segmentation maps mean, and what purpose do they achieve during training and inference?
> 
> Thank you in advance!
> 
> Regards.

This is for **Deep Supervision**.It helps alleviate issues such as vanishing gradients and slow convergence during training, thereby enhancing the model's feature representation capabilities.

**Comment by ahinchoi** [comment]
Thank you for the quick and clear answer!

Just one more thing - there seems to be a test configuration in the config files but no testing script under the /tools directory.

Should I just load the best checkpoint into the model and input my custom data?

Again, thank you for your consideration.

**Comment by takaniwa** [comment]
> Just one more thing - there seems to be a test configuration in the config files but no testing script under the /tools directory.

you are right.

**Comment by ahinchoi** [comment]
Thank you very much for your assistance! 

Have a great day.
